//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJYDataLib
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://schemas.datacontract.org/2004/07/XJYDataLib")]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AuditYearField;
        
        private System.DateTime BeginDateField;
        
        private string CustomerIDField;
        
        private string CustomerNameField;
        
        private System.DateTime EndDateField;
        
        private string ProjectIDField;
        
        private string ProjectNameField;
        
        private string WP_GUIDField;
        
        private string WP_HostField;
        
        private string WP_PathNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuditYear
        {
            get
            {
                return this.AuditYearField;
            }
            set
            {
                this.AuditYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginDate
        {
            get
            {
                return this.BeginDateField;
            }
            set
            {
                this.BeginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectID
        {
            get
            {
                return this.ProjectIDField;
            }
            set
            {
                this.ProjectIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName
        {
            get
            {
                return this.ProjectNameField;
            }
            set
            {
                this.ProjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WP_GUID
        {
            get
            {
                return this.WP_GUIDField;
            }
            set
            {
                this.WP_GUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WP_Host
        {
            get
            {
                return this.WP_HostField;
            }
            set
            {
                this.WP_HostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WP_PathName
        {
            get
            {
                return this.WP_PathNameField;
            }
            set
            {
                this.WP_PathNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResult", Namespace="http://schemas.datacontract.org/2004/07/XJYDataLib")]
    public partial class RequestResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContentsField;
        
        private string DescriptsField;
        
        private string MethodNameField;
        
        private string StatusField;
        
        private int StatusCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contents
        {
            get
            {
                return this.ContentsField;
            }
            set
            {
                this.ContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripts
        {
            get
            {
                return this.DescriptsField;
            }
            set
            {
                this.DescriptsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IXJYDataService")]
public interface IXJYDataService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXJYDataService/ServiceTest", ReplyAction="http://tempuri.org/IXJYDataService/ServiceTestResponse")]
    string ServiceTest(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXJYDataService/ServiceTest", ReplyAction="http://tempuri.org/IXJYDataService/ServiceTestResponse")]
    System.Threading.Tasks.Task<string> ServiceTestAsync(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXJYDataService/DownloadFile", ReplyAction="http://tempuri.org/IXJYDataService/DownloadFileResponse")]
    XJYDataLib.RequestResult DownloadFile(XJYDataLib.CustomerInfo customerInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXJYDataService/DownloadFile", ReplyAction="http://tempuri.org/IXJYDataService/DownloadFileResponse")]
    System.Threading.Tasks.Task<XJYDataLib.RequestResult> DownloadFileAsync(XJYDataLib.CustomerInfo customerInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXJYDataService/ImportData2Eas", ReplyAction="http://tempuri.org/IXJYDataService/ImportData2EasResponse")]
    XJYDataLib.RequestResult ImportData2Eas(XJYDataLib.CustomerInfo customerInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXJYDataService/ImportData2Eas", ReplyAction="http://tempuri.org/IXJYDataService/ImportData2EasResponse")]
    System.Threading.Tasks.Task<XJYDataLib.RequestResult> ImportData2EasAsync(XJYDataLib.CustomerInfo customerInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IXJYDataServiceChannel : IXJYDataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class XJYDataServiceClient : System.ServiceModel.ClientBase<IXJYDataService>, IXJYDataService
{
    
    public XJYDataServiceClient()
    {
    }
    
    public XJYDataServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public XJYDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public XJYDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public XJYDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ServiceTest(string message)
    {
        return base.Channel.ServiceTest(message);
    }
    
    public System.Threading.Tasks.Task<string> ServiceTestAsync(string message)
    {
        return base.Channel.ServiceTestAsync(message);
    }
    
    public XJYDataLib.RequestResult DownloadFile(XJYDataLib.CustomerInfo customerInfo)
    {
        return base.Channel.DownloadFile(customerInfo);
    }
    
    public System.Threading.Tasks.Task<XJYDataLib.RequestResult> DownloadFileAsync(XJYDataLib.CustomerInfo customerInfo)
    {
        return base.Channel.DownloadFileAsync(customerInfo);
    }
    
    public XJYDataLib.RequestResult ImportData2Eas(XJYDataLib.CustomerInfo customerInfo)
    {
        return base.Channel.ImportData2Eas(customerInfo);
    }
    
    public System.Threading.Tasks.Task<XJYDataLib.RequestResult> ImportData2EasAsync(XJYDataLib.CustomerInfo customerInfo)
    {
        return base.Channel.ImportData2EasAsync(customerInfo);
    }
}
